name: Build and update web dist folder

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GH_PAT || github.token }}

    - name: Use Node.js lts/iron
      uses: actions/setup-node@v4
      with:
        node-version: lts/iron

    - name: Build
      run: |
        npm install
        npm -g install bower
        bower install
        grunt build
    - name: Update dist
      run: |
        git config --global user.email "18280396+Lastorder-DC@users.noreply.github.com"
        git config --global user.name "Lastorder-DC BuildBot"
        git add .
        git commit -m "[skip ci] Update dist for ${{ github.ref }}"
        git push
